### ISSUE TITLE
build stuck with the same warning repeated again and again

### ISSUE THREAD

**Issue by Aqsa-physics** [patscott/gambit_1.2#4]
I am building gambit without Mathematica and at the last step of 

`make -jn gambit`

I am getting the following warning over and over again and the build process is not proceeding forward. This is the warning I am getting regarding flexiblesusy:

In file included from /usr/include/c++/7/cassert:44:0, from src/gsl_utils.hpp:26, from src/root_finder.hpp:33, from src/standard_model.cpp:33: src/gsl_utils.hpp: In instantiation of ‘void flexiblesusy::copy(const Eigen::DenseBase<Derived>&, gsl_vector*) [with Derived = Eigen::Matrix<double, 1, 1, 0, 1, 1>]’: src/root_finder.hpp:223:8: required from ‘static int flexiblesusy::Root_finder<dimension>::gsl_function(const gsl_vector*, void*, gsl_vector*) [with long unsigned int dimension = 1]’ src/root_finder.hpp:139:27: required from ‘int flexiblesusy::Root_finder<dimension>::find_root(const Vector_t&) [with long unsigned int dimension = 1; flexiblesusy::Root_finder<dimension>::Vector_t = Eigen::Matrix<double, 1, 1, 0, 1, 1>]’ src/root_finder.hpp:263:21: required from ‘int flexiblesusy::Root_finder<dimension>::solve(const VectorXd&) [with long unsigned int dimension = 1; Eigen::VectorXd = Eigen::Matrix<double, -1, 1>]’ src/standard_model.cpp:4593:1: required from here src/gsl_utils.hpp:97:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare] assert(dim == dst->size);

This is where my build is stuck with the same above warning repeated over and over.

Any help will be useful. Thank you.

**Comment by pathron** [comment]
The problem is the build is not making progress or taking too long?   FlexibleSUSY can take some time to build and there has been specific problems with some compilers where that was much worse.

Which FlexibleSUSY models are you building with ?  When you wrote `make -jn gambit` what number did you use for n?

**Comment by Aqsa-physics** [comment]
Yes, I had faced similar problem while installing GEANT4. build was taking a lot of time. (it was few years back so I kind of forgot how I solved it)
In here, I started with j4, 
I got the following error in Generating modules_harvested

`  Updated Elements/include/gambit/Elements/module_types_rollcall.hpp
Harvesting types from headers...
libtool:   error: require no space between '-L' and '-o'
Makefile:579: recipe for target 'libRestFrames.la' failed
make[6]: *** [libRestFrames.la] Error 1
Makefile:508: recipe for target 'all' failed
make[5]: *** [all] Error 2
Makefile:539: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
CMakeFiles/restframes.dir/build.make:113: recipe for target 'restframes-prefix/src/restframes-stamp/restframes-build' failed
make[3]: *** [restframes-prefix/src/restframes-stamp/restframes-build] Error 2
CMakeFiles/Makefile2:5339: recipe for target 'CMakeFiles/restframes.dir/all' failed
make[2]: *** [CMakeFiles/restframes.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....`

Later followed by the same reoccuring error

`In file included from /usr/include/c++/7/cassert:44:0,
                 from src/gsl_utils.hpp:26,
                 from src/root_finder.hpp:33,
                 from src/standard_model.cpp:33:
src/gsl_utils.hpp: In instantiation of ‘void flexiblesusy::copy(const Eigen::DenseBase<Derived>&, gsl_vector*) [with Derived = Eigen::Matrix<double, 1, 1, 0, 1, 1>]’:
src/root_finder.hpp:223:8:   required from ‘static int flexiblesusy::Root_finder<dimension>::gsl_function(const gsl_vector*, void*, gsl_vector*) [with long unsigned int dimension = 1]’
src/root_finder.hpp:139:27:   required from ‘int flexiblesusy::Root_finder<dimension>::find_root(const Vector_t&) [with long unsigned int dimension = 1; flexiblesusy::Root_finder<dimension>::Vector_t = Eigen::Matrix<double, 1, 1, 0, 1, 1>]’
src/root_finder.hpp:263:21:   required from ‘int flexiblesusy::Root_finder<dimension>::solve(const VectorXd&) [with long unsigned int dimension = 1; Eigen::VectorXd = Eigen::Matrix<double, -1, 1>]’
src/standard_model.cpp:4593:1:   required from here
src/gsl_utils.hpp:97:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    assert(dim == dst->size);
`

These two errors pattern was repeated for j3 and j2 as well.

But for j1 I just got the later reocurring error. Generating modules_harvested step was completed without error.

**Comment by patscott** [comment]
Hi Aqsa -- can you try with the latest version (https://github.com/patscott/gambit_1.4) please?  This version is not actually supported or updated any longer, and the issue may well be fixed in the latest one.

**Comment by Aqsa-physics** [comment]
Hey Pat,
Thanks for suggesting me this really appreciate it. But unfortunately it is giving me the same warning and build got stuck there. How long does it usually take to build gambit?
Today I will try on another system that I have. Till now I was trying to install it on my ubuntu. I have a centOS as well maybe I can try there. Will keep posted here.
Thank you !

**Comment by Aqsa-physics** [comment]
Hey @patscott , seems like I won't be able to access CentOS soon. I can only reach to it through remote access right now which is not working very smooth, unfortunately. I would have to stick to my ubuntu.
So as per your suggestion, I tried the latest version but the problem remains the same. Since there is no error coming up just repeated warning which stops my build I am unable to completely understand it to debug.
I hope there is some solution to it.
If you need any specifications from my system let me know.
Thank you.

**Comment by pathron** [comment]
The warning is something I have seen a lot before and as far as I recall depends on what eigen version you used, and is not normally a problem.  I have not seen a case where FlexibleSUSY does not compiile and that warning is all you get, but I have seen cases where FlexibleSUSY is taking a  long time to build.

Can you say how long it is actually taking?   

Can you also say which FlexibleSUSY models you were trying to build if you know and  just paste in the cmake command you used and the output from it?  Telling us how much memory you have may also help, though that would lead to crashing and/or hanging for a long timeat the end, not repeated spewing of that warning.

**Comment by patscott** [comment]
I'm going to move this issue over to the 1.4 repo.

It should normally take 30 mins or so to build gambit with e.g. 4-8 cores.  Probably 2 hr if you use only one core.

The warnings are not an issue, and can be ignored.  You just have to wait for the build to complete in that case.  

The first error is about RestFrames.  You can try building without RestFrames by doing 
``
cmake -DEXCLUDE_RESTFRAMES=True ..
``
